version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=34.251.233.38
      - DB_NAME=GEMS-UAT
      - DB_USER=SimplicityWebSQL
      - DB_PASSWORD=true-tirade-muddy23
      - DB_PORT=1433
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=3001
    volumes:
      - backend-logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend-logs: